Update readme.md
uriyang/callorie pull request #1
Opened 2019-04-03 15:54 UTC by uriyang

2019-04-04 00:25 UTC, ByBogon commented
감사합니다!

2019-04-04 01:25 UTC, logic0319 approved these changes

2019-04-04 04:10 UTC, super-fishz requested changes

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- 반응 형 스트림 프로그래밍 지원
```suggestion
- 반응형 스트림 프로그래밍 지원
```
형용사니까 붙이는게 맞는 것 같아요 :)

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- 작다! 무게는 [7kB](https://github.com/staltz/callbag-basics/tree/master/dist)에 불과하다.
```suggestion
- 작다! 라이브러리의 크기는 [7kB](https://github.com/staltz/callbag-basics/tree/master/dist)에 불과합니다!
```
좀 더 구어체로 변경했어요

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- 반응 형 스트림 프로그래밍 지원
iterable 은 번역안하는데 reactive 만 번역하기도 일관성이 없어서, 
iterable, reactive 등을 어떻게 표기할 것인지 정하면 좋겠습니다 :)

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- 빠르다! xstream 및 RxJS보다 [빠르다](https://github.com/staltz/callbag-basics/tree/master/perf)
```suggestion
- 빠르다! xstream 및 RxJS보다 [빠릅니다](https://github.com/staltz/callbag-basics/tree/master/perf)
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- 확장성: 코어 라이브러리 없습니다.! 모두 유틸리티 함수입니다.
```suggestion
- 확장성: 코어 라이브러리가 없습니다. callbag은 모두 유틸리티 함수입니다.
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +Observable과 (비동기) Iterable 사이의 하이브리드를 상상해보십시오. 그게 바로 콜백에 관한 전부입니다. 또한, [callbag spec](https://github.com/callbag/callbag)을 따르는 몇 가지 간단한 콜백(callbacks)으로 구현되기 때문에 코드가 가볍다. 그 결과, 작고 빠릅니다.
```suggestion
Observable과 (비동기) Iterable 를 같이 사용하는 상상을 해보세요. 그게 바로 callbag 입니다. 또한, [callbag spec](https://github.com/callbag/callbag)을 따르는 몇 가지 간단한 콜백(callbacks)으로 구현되기 때문에 코드가 가볍습니다. 그 결과로 callbag은 작고 빠릅니다.
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +연산자 및 팩토리 Import:
```suggestion
연산자 및 팩토리를 Import 하는 방법:
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +### 반응 프로그래밍 예제
```suggestion
### 반응형 프로그래밍 예제
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +<button>요소 에 대한 클릭 이벤트의 XY 좌표를 출력 합니다:
```suggestion
<button>요소의 클릭 이벤트를 받아 XY 좌표를 출력 합니다:
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +아래는 포함 된 함수 목록입니다.
```suggestion
callbag에 포함된 함수 목록입니다.
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- **puller sink**: 데이터를 적극적으로 요청하는 싱크
```suggestion
- **puller sink**: 데이터를 소스에 능동적으로 요청하는 받는 callbag
```

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +- **operator**: 어떤 작업을 적용하는 다른 callbag 기반의 callbaga
```suggestion
- **operator**: 어떤 작업의 결과로 생성된 callbag을 기초로 하는 callbag
```
와 이거 말 어렵다

2019-04-04 04:10 UTC, super-fishz commented on readme.md
> +## 기여
```suggestion
## 기여방법
```

2019-04-04 05:59 UTC, uriyang commented on readme.md
> +- **operator**: 어떤 작업을 적용하는 다른 callbag 기반의 callbaga
뭔가 애매하죠??ㅎ

2019-04-04 12:24 UTC, ByBogon commented on readme.md
> +- **operator**: 어떤 작업의 결과로 생성된 callbag을 기초로 하는 callbag
어떤 operation을 사용하는 다른 callbag을 기초로 하는 callbag

2019-04-05 13:56 UTC, uriyang commented on readme.md
> +- 반응 형 스트림 프로그래밍 지원
반응형을 reactive로 다 바꿔도 괜찮을 것 같아요^^

2019-04-06 15:47 UTC, merged